name: idea_vault_by_amit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^1.5.0
  provider: ^6.0.0
  fluttertoast: ^8.2.1
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


dependency_overrides:
  path_provider_linux: any
  path_provider_windows: any
  shared_preferences_linux: any
  shared_preferences_windows: any
  url_launcher_linux: any
  url_launcher_windows: any
  app_links: any
